# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fellow', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vita', models.TextField(blank=True, verbose_name='\u0411\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u043e\u0444\u043d\u0430')),
                ('post', models.CharField(blank=True, max_length=50, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('post_sci', models.CharField(blank=True, max_length=50, verbose_name='\u0423\u0447\u0451\u043d\u0430\u044f \u0441\u0442\u0435\u043f\u0435\u043d\u044c')),
                ('post_academy', models.CharField(blank=True, max_length=50, verbose_name='\u0423\u0447\u0451\u043d\u043e\u0435 \u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u0434')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('bibliography', models.TextField(verbose_name='\u0411\u0438\u0431\u043b\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u0447\u0435\u0441\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('link', models.URLField(blank=True, verbose_name='\u0411\u0438\u0431\u043b\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u0447\u0435\u0441\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='igc.Fellow')),
            ],
        ),
    ]
