# Generated by Django 2.2.1 on 2019-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Короткое название')),
                ('long_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Сообщество будет видно для любых зарегистрированных пользователей', verbose_name='Открытое сообщество')),
                ('open_registration', models.BooleanField(default=False, help_text='Любой желающий зарегистрированный пользователь может вступить в сообщество', verbose_name='Свободная регистрация')),
                ('show_members', models.BooleanField(default=False, help_text='Показывать список участников для любого зарегистрированного пользователя если сообщество публичное', verbose_name='Показывать участников')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_invited', models.BooleanField(default=False, verbose_name='По приглашению')),
            ],
            options={
                'verbose_name': 'Участник сообщества',
                'verbose_name_plural': 'Участники сообществ',
            },
        ),
    ]
