# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellow',
            name='biography',
        ),
        migrations.AddField(
            model_name='fellow',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='fellow',
            name='post_academy',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0423\u0447\u0451\u043d\u043e\u0435 \u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='fellow',
            name='post_sci',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0423\u0447\u0451\u043d\u0430\u044f \u0441\u0442\u0435\u043f\u0435\u043d\u044c'),
        ),
        migrations.AddField(
            model_name='fellow',
            name='vita',
            field=models.TextField(blank=True, verbose_name='\u0411\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u043e\u0444\u043d\u0430'),
        ),
    ]
