# Generated by Django 2.2.1 on 2019-05-30 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igc', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fellow', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vita', models.TextField(blank=True, verbose_name='Биография')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Номер телеофна')),
                ('post', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('post_sci', models.CharField(blank=True, max_length=50, verbose_name='Учёная степень')),
                ('post_academy', models.CharField(blank=True, max_length=50, verbose_name='Учёное звание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('bibliography', models.TextField(verbose_name='Библиографичесая ссылка')),
                ('link', models.URLField(blank=True, verbose_name='Библиографичесая ссылка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='igc.Fellow')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.AddField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='igc.Community'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_member', to='igc.Fellow'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community', 'member')},
        ),
    ]
