# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fellow_photos', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
