# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0002_auto_20170620_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='post',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
