# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0002_auto_20170823_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellow',
            options={'verbose_name': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a', 'verbose_name_plural': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f', 'verbose_name_plural': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e \u043f\u0440\u0438\u0433\u043b\u0430\u0448\u0435\u043d\u0438\u044e'),
        ),
        migrations.AlterField(
            model_name='community',
            name='long_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_member', to='igc.Fellow'),
        ),
    ]
