# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0004_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
