# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0005_auto_20170620_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='\u0413\u043e\u0434'),
        ),
    ]
