# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igc', '0006_auto_20170620_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u0434'),
        ),
    ]
